services:
#    lexxpavlov.sonata.admin.settings_categories:
#        class: Lexxpavlov\SettingsBundle\Admin\CategoryAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: "Settings", label: "Categories", label_catalogue: "messages", icon: '<i class="fa fa-wrench"></i>' }
#        arguments:
#            - ~
#            - Lexxpavlov\SettingsBundle\Entity\Category
#            - ~
#            - '@lexxpavlov_settings.settings'
#        calls:
#            - [ setTranslationDomain, [messages]]

    lexxpavlov.sonata.admin.settings:
        class: Lexxpavlov\SettingsBundle\Admin\SettingsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Settings", label: "Settings", label_catalogue: "messages", icon: '<i class="fa fa-wrench"></i>' }
        arguments:
            - ~
            - Lexxpavlov\SettingsBundle\Entity\Settings
            - ~
            - '@lexxpavlov_settings.settings'
        calls:
            - [ setTranslationDomain, [messages]]
